server:
  port: 8100

spring:
  datasource:
    username: juntao
    password: password
    url: jdbc:mysql://localhost:3306/ladder
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: java.text.SimpleDateFormat
