CREATE TABLE books
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR (256),
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY(id)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;